version: "3"
services:
  strapi:
    container_name: strapi
    image: strapi:latest
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: strapiDB
      DATABASE_PORT: 5432
      DATABASE_NAME: postgres
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: safepassword
      JWT_SECRET: bwdmkE9MrloiJUGz7oiz5Q==
      ADMIN_JWT_SECRET: Tj3LkCwzKIok6+zIPKO1OA==
      APP_KEYS: EabbM6zjrxBTtywZ2Hr3RA==,TJjdzKOMTv/uxBg/WBw9RA==,TE9BcGU6rFBgBUwd2MX4xQ==,/JveKmmdHIjONWO1Q9ZAPA==
      NODE_ENV: development
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads   
    ports:
      - '1337:1337'
    networks:
      - bruno
    command: strapi develop # Ajout de cette ligne  
    depends_on:
      - strapiDB

  strapiDB:
    container_name: strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: safepassword
      POSTGRES_DB: postgres
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    networks:
      - bruno
  
  frontend:
    container_name: frontend
    build:
        context : ./opsci-strapi-frontend
        dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - bruno
    depends_on:
      - strapiDB
      
  dump:
    container_name: db-dump
    image: postgres:12.0-alpine
    env_file: 
      - .env
    command: ["sh", "-c", "export PGPASSWORD=safepassword && pg_dumpall -h strapiDB -U strapi > /dump/backup.sql"]

    volumes:
      - ./dump:/dump
    depends_on:
      - strapiDB
    networks:
      - bruno
      
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - '2181:2181'
    expose:
      - '2181'
    networks:
      - bruno

  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: kafka
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092,
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKAJS_NO_PARTITIONER_WARNING: '1'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_NO_LISTENER_AUTHENTICATION_PLAINTEXT: 'true'
      KAFKA_NO_LISTENER_AUTHENTICATION_SSL: 'true'
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_LOG_DIRS: /kafka/logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - bruno


  product-producer:
      image: arthurescriou/product-producer:1.0.0
      container_name: product-producer
      build:
        context : ./productproducer
        dockerfile: Dockerfile
      environment:
        BROKER_1: kafka:9092
        BROKER_2: kafka:9092
        BROKER_3: kafka:9092
        STRAPI_TOKEN: 'a35bf689cad1065b7812b9a35422f90a9e40c4c1054feeb4583abd344d936f6fc1bbbb7bfa9831e5b3d211e424803a68852e4e93c5de541a5e5a88edfd5c39225e8ea9a86ee7c14240c362243978636138f21666b2bf00a13a2bfff3f6efeab031691b397e62bdb2cfc1483a19f6975aada202cae08517d09a9a0f90c012b8e0'
        STRAPI_URL: http://strapi:1337
        TOPIC: product
        ERROR_TOPIC: errors
        FILE_NAME: products.csv
      volumes:
          - ./productproducer/products.csv:/var/lib/products.csv  
      depends_on:
          - kafka
          - strapi
      networks:
          - bruno
  product-consumer:
      image: arthurescriou/product-consumer:latest
      container_name: product-consumer
      build:
          context: ./productconsumer
          dockerfile: Dockerfile
      environment:
        BROKER_1: kafka:9092
        BROKER_2: kafka:9092
        BROKER_3: kafka:9092
        STRAPI_TOKEN: 'a35bf689cad1065b7812b9a35422f90a9e40c4c1054feeb4583abd344d936f6fc1bbbb7bfa9831e5b3d211e424803a68852e4e93c5de541a5e5a88edfd5c39225e8ea9a86ee7c14240c362243978636138f21666b2bf00a13a2bfff3f6efeab031691b397e62bdb2cfc1483a19f6975aada202cae08517d09a9a0f90c012b8e0'
        STRAPI_URL: http://strapi:1337
        TOPIC: product
        BEGINNING: 'false' 
        ERROR_TOPIC: errors
      depends_on:
            - kafka
            - strapi
      networks:
            - bruno
       
  
  event-producer:
      image: arthurescriou/event-producer:1.0.3
      container_name: event-producer
      build:
          context : ./eventproducer
          dockerfile: Dockerfile   
      environment:
          BROKER_1: kafka:9093
          BROKER_2: kafka:9093
          BROKER_3: kafka:9093
          TOPIC: event
          FILE_NAME: events.csv
          ERROR_TOPIC: errors
      volumes:
          - ./eventproducer/events.csv:/var/lib/events.csv  
      
      networks:
          - bruno

      depends_on:
          - kafka
          - strapi
          
          
  event-consumer:
      image: arthurescriou/event-consumer:1.0.0
      container_name: event-consumer
      build:
          context: ./eventconsumer
          dockerfile: Dockerfile
      environment:
          BROKER_1: kafka:9092
          BROKER_2: kafka:9092
          BROKER_3: kafka:9092
          STRAPI_TOKEN: 'a35bf689cad1065b7812b9a35422f90a9e40c4c1054feeb4583abd344d936f6fc1bbbb7bfa9831e5b3d211e424803a68852e4e93c5de541a5e5a88edfd5c39225e8ea9a86ee7c14240c362243978636138f21666b2bf00a13a2bfff3f6efeab031691b397e62bdb2cfc1483a19f6975aada202cae08517d09a9a0f90c012b8e0'
          STRAPI_URL: http://strapi:1337
          TOPIC: event
          BEGINNING: "false"
          ERROR_TOPIC: errors
    
      networks:
          - bruno

      depends_on:
          - kafka
          - strapi
  stock-producer:
      image: arthurescriou/stock-producer:1.0.1
      container_name: stock-producer
      build:
          context: ./stockproducer
          dockerfile: Dockerfile
      environment:
          BROKER_1: kafka:9093
          BROKER_2: kafka:9093
          BROKER_3: kafka:9093
          TOPIC: stock
          FILE_NAME: stocks.csv
      networks:
          - bruno
      depends_on:
          - kafka
          - strapi
          
  stock-consumer:
      image: arthurescriou/stock-consumer:1.0.0
      container_name: stock-consumer
      build:
          context: ./stockconsumer
          dockerfile: Dockerfile
      environment: 
          BROKER_1: kafka:9092
          BROKER_2: kafka:9092
          BROKER_3: kafka:9092
          STRAPI_TOKEN: 'a35bf689cad1065b7812b9a35422f90a9e40c4c1054feeb4583abd344d936f6fc1bbbb7bfa9831e5b3d211e424803a68852e4e93c5de541a5e5a88edfd5c39225e8ea9a86ee7c14240c362243978636138f21666b2bf00a13a2bfff3f6efeab031691b397e62bdb2cfc1483a19f6975aada202cae08517d09a9a0f90c012b8e0'
          STRAPI_URL: http://strapi:1337
          TOPIC: stock
          BEGINNING: "false"
          ERROR_TOPIC: errors
      networks:
          - bruno
      depends_on:
          - kafka
          - strapi
      

volumes:
  strapi-data:

networks:
  bruno:
    name: bruno
    driver: bridge  # Correction ici
